In [7]:
import numpy as np
import tqdm

In [8]:
data = np.load('pythonxx/A01T.npz')

In [9]:
signal = data['s']
etype = data['etyp']
epos = data['epos']
edur = data['edur']

In [67]:
# 每个event单独有一个array，包括这个event在etype中出现位置的index
index769 = np.where(etype == 769)
index769 = index769[0]

index770 = np.where(etype == 770)
index770 = index770[0]

index771 = np.where(etype == 771)
index771 = index771[0]

index772 = np.where(etype == 772)
index772 = index772[0]

index769

array([ 14,  16,  28,  30,  32,  40,  42,  46,  57,  71,  85, 104, 107,
       109, 116, 120, 129, 135, 150, 160, 166, 172, 182, 205, 214, 222,
       224, 239, 247, 259, 271, 273, 279, 289, 301, 305, 310, 312, 324,
       328, 330, 356, 368, 372, 376, 380, 384, 394, 408, 416, 418, 432,
       457, 465, 469, 473, 475, 477, 479, 500, 505, 529, 552, 556, 562,
       566, 572, 576, 585, 593, 597, 602], dtype=int64)

In [83]:
#769
epos769 = []
for i in range(len(index769)):
    epos769.append(epos[index769[i]][0])
    
diff_epos769 = []
for i in range(len(index769)-1):
    diff_epos769.append(epos[index769[i] + 1][0] - epos[index769[i]][0])


    
#770
epos770 = []
for i in range(len(index770)):
    epos770.append(epos[index770[i]][0])
    
diff_epos770 = []
for i in range(len(index770)):
    diff_epos770.append(epos[index770[i] + 1][0] - epos[index770[i]][0])
    

    
#771
epos771 = []
for i in range(len(index771)):
    epos771.append(epos[index771[i]][0])
    
diff_epos771 = []
for i in range(len(index771)):
    diff_epos771.append(epos[index771[i] + 1][0] - epos[index771[i]][0])



#772
epos772 = []
for i in range(len(index772)):
    epos772.append(epos[index772[i]][0])
    
diff_epos772 = []
for i in range(len(index772)):
    diff_epos772.append(epos[index772[i] + 1][0] - epos[index772[i]][0])

In [84]:
len(diff_epos769), len(diff_epos770), len(diff_epos771), len(diff_epos772)

(71, 72, 72, 72)

In [105]:
#每一个event对应edur里的数字 都是313
edur769 = []
for i in range(len(index769)):
    edur769.append(edur[index769[i]][0])
    
edur770 = []
for i in range(len(index770)):
    edur770.append(edur[index770[i]][0])
    
edur771 = []
for i in range(len(index771)):
    edur771.append(edur[index771[i]][0])
    
edur772 = []
for i in range(len(index772)):
    edur772.append(edur[index772[i]][0])

In [62]:
etype

array([[32766],
       [  276],
       [32766],
       [  277],
       [32766],
       [ 1072],
       [32766],
       [  768],
       [  772],
       [  768],
       [  771],
       [  768],
       [  770],
       [  768],
       [  769],
       [  768],
       [  769],
       [  768],
       [  770],
       [  768],
       [  771],
       [  768],
       [  772],
       [  768],
       [  770],
       [  768],
       [  771],
       [  768],
       [  769],
       [  768],
       [  769],
       [  768],
       [  769],
       [  768],
       [  772],
       [  768],
       [  770],
       [  768],
       [  770],
       [  768],
       [  769],
       [  768],
       [  769],
       [  768],
       [  771],
       [  768],
       [  769],
       [  768],
       [  770],
       [  768],
       [ 1023],
       [  772],
       [  768],
       [  772],
       [  768],
       [  771],
       [  768],
       [  769],
       [  768],
       [  772],
       [  768],
       [  772],
       [

In [60]:
epos

array([[     1],
       [     1],
       [ 29684],
       [ 29684],
       [ 49956],
       [ 49956],
       [ 91519],
       [ 91869],
       [ 92369],
       [ 93872],
       [ 94372],
       [ 95790],
       [ 96290],
       [ 97742],
       [ 98242],
       [ 99750],
       [100250],
       [101861],
       [102361],
       [103778],
       [104278],
       [105828],
       [106328],
       [107759],
       [108259],
       [109757],
       [110257],
       [111663],
       [112163],
       [113558],
       [114058],
       [115530],
       [116030],
       [117474],
       [117974],
       [119441],
       [119941],
       [121561],
       [122061],
       [123569],
       [124069],
       [125635],
       [126135],
       [127671],
       [128171],
       [129737],
       [130237],
       [131807],
       [132307],
       [133887],
       [133887],
       [134387],
       [135799],
       [136299],
       [137830],
       [138330],
       [139783],
       [140283],
       [141744

In [38]:
edur

array([[    0],
       [29682],
       [    0],
       [20271],
       [    0],
       [41562],
       [    0],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [ 1875],
       [  313],
       [

In [ ]:
diff = []
for i in range(0, 200):
    x = epos[8+2*i] - epos[7+2*i]
    diff.append(x)
    print(x)

In [ ]:
def findtype(data, classnum):
    data1 = np.load(data)
    signal = data1['s']
    etype = data1['etyp']
    epos = data1['epos']
    edur = data1['edur']
    x = etype[etype == classnum]
    pa = epos[etype == classnum]
    pd = edur[etype == classnum]
    ps = pa + pd
    sigarr = []
    for i in range(len(pd)):
        sigarr.append(signal[pa[i]:ps[i]])
    finsigarr = np.stack(sigarr, axis= 0)
    
    return finsigarr